### ISSUE TITLE
Game crashes when using Confounding Breath on Wither Skeleton due to NoSuchMethodError

### ISSUE THREAD

**Issue by Psither** [Psither/AdditionalDragons#1]
I am unable to replicate this bug.  Can you provide more details as to what versions you are using for Minecraft, DragonSurvival, and AdditionalDragons?
![wither_skeleton](https://github.com/user-attachments/assets/7074f608-a841-484e-9a08-6f5de7b24cf5)

Additionally, DS 1.20 is developed for Neoforged, and using Forge may potentially cause unexpected results, even if there are supposed to be no breaking changes in their 1.20 split from Forge.

**Comment by ZaliahVertex** [comment]
Of course, here are the versions for what you requested:

- Minecraft 1.20.1
- DragonSurvival 1.20.1-18.07.2024
- Additional Dragons 0.2.3_1.20.1
- Further more, I am using Forge 47.3.0

Additional Dragons is listed as having both a Forge and a NeoForge version in the curseforge launcher, perhaps this is something to look into if the issue is to be close due to No Repro?

Lastly, please find below a copy of my crashlog:

[crash-2024-09-30_09.50.58-server.txt](https://github.com/user-attachments/files/17210275/crash-2024-09-30_09.50.58-server.txt)
[crash-2024-09-30_09.13.40-server.txt](https://github.com/user-attachments/files/17210276/crash-2024-09-30_09.13.40-server.txt)
[crash-2024-09-30_09.05.15-server.txt](https://github.com/user-attachments/files/17210277/crash-2024-09-30_09.05.15-server.txt)

**Comment by Psither** [comment]
The method in question was renamed in the latest patch for 1.20.  It should be fixed in the latest update I just pushed.
